### ISSUE TITLE
GaverStehfest Algorithm

### ISSUE THREAD

**Issue by theogf** [jlapeyre/InverseLaplace.jl#11]
Hi,

Do you think the Gaver-Stehfest algorithm would be a good feature for this package?  (https://arxiv.org/pdf/1305.0715.pdf)
I could submit a PR if you are interested

**Comment by jlapeyre** [comment]
Hi Sorry about the delay. Didn't get a notification for some reason. If you are still interested, yes, I think it would make a great addition.
