### ISSUE TITLE
`talbot` yields NaN where it shouldn't

### ISSUE THREAD

**Issue by moustachio-belvedere** [jlapeyre/InverseLaplace.jl#12]
This is related, but different to, issue #5. Apologies if I have misunderstood something from your answer in that issue.

I have a function defined in the time domain as `J(t) = 1 - exp(-t)` which yields `0.0` at `t=0.0`. The Laplace transform of this function is Jbar(s) = `1/s - 1/(s + 1)`. 

For various reasons, the inputs and outputs should be of type `Float64`. However, recalling what you said about using `BigFloat`, I defined a few different versions of this:

```
J_i(s) = 1/s - 1/(s + 1);

J_f64(s) = 1.0/s - 1.0/(s + 1.0);

```
For all numerically computed values I get `NaN`:

```
julia> talbot(s -> J_i(s), big(0.0))
NaN

julia> talbot(s -> J_f64(s), 0)
NaN

julia> talbot(s -> J_f64(s), 0.0)
NaN

julia> talbot(s -> J_f64(s), big(0))
NaN
```

Is this just a corner case that causes numerical instabilities? It is strange because it happens for all the creep moduli (https://en.wikipedia.org/wiki/Creep_%28deformation%29) in my program that are defined in terms of their Laplace transform, and I am sure that they all have well defined values at `t=0.0` in the time domain.

Note that it gets closer to the correct value for extremely small values of t, and this is the approximation I am currently using to get round the issue:

```
julia> talbot(s -> J_f64(s), 1e-5)
9.999950291077498e-6

julia> talbot(s -> J_f64(s), 1e-15)
2.4006857918196764e-12
```

**Comment by jlapeyre** [comment]
Yes, maybe two large quantities are subtracted, or something like that. I did not look at it in detail.
Note that you can do this:
```julia
julia> talbot(J_i, 1//big(10)^100)
4.285143745988771853544147570511029611988248719406574944687873966688982255945018e-104

julia> talbot(J_i, 1//big(10)^1000)
0.0
```

**Comment by moustachio-belvedere** [comment]
OK Thanks  John. We will use a similar workaround to that you suggested.
