### ISSUE TITLE
Excessive memory allocation when evaluating w(t)::Complex compared to w(t)::Float64

### ISSUE THREAD

**Issue by elisno** [jlapeyre/InverseLaplace.jl#2]
The following code solves a linear system of equations in the Laplace domain. Then it uses Weeks' method to determine the inverse Laplace transform of the first element of the solution.

```
using InverseLaplace
using Base.LinAlg.LAPACK: gesv!

######  Function definitions

function randmatvec(N::Int64)
    # Initialize the matrix A  and the vector b for the equation (sI - A)x = b
    A = complex.(rand(N^2,N^2),rand(N^2,N^2))
    b = zeros(Complex{Float64},N^2)
    b[N*(N-1)] = complex.(1.0,0.0)
    return (A, b)
end

function matrixequation!(A::AbstractArray{T},s::T) where T
    # Returns the l.h.s. of the equation (sI - A)x = b
    A .= s.*eye(A) .- A
    return A
end

function solvematrixequation!(A::AbstractArray{T},b::AbstractVector{T},s::T) where T
    # Return the first element of the solution of (sI - A)x = b
    gesv!(matrixequation!(A,s),b)
    return b[1]
end

function laplaceelement(s::Complex{Float64}, N::Int64)
    # Wrapper for first element of x(s) = (sI -A)⁻¹b
    (A,b) = randmatvec(N)
    return solvematrixequation!(A,b,s)
end
######


N = 8
laplaceelement(s::Complex) = laplaceelement(s, N)

trange = collect(linspace(0.0,3.0,1E5))

begin
    println("Float64")
    @time w1 = Weeks.(laplaceelement)
    @time w1.(trange)
    println("")

    println("Complex{Float64}")
    @time w2 = Weeks.(laplaceelement,datatype=Complex)
    @time w2.(trange)
    println("")
end
```
After running the `begin` block twice, I get the following output:

```
Float64
  0.044574 seconds (2.05 k allocations: 24.277 MiB, 16.83% gc time)
  0.267619 seconds (6 allocations: 781.484 KiB)

Complex{Float64}
  0.042009 seconds (2.32 k allocations: 24.293 MiB, 10.89% gc time)
  0.869980 seconds (37.80 M allocations: 1.030 GiB, 18.26% gc time)

```

The evaluation of the complex `w(t)` takes three times as long as the real one.
I would have expected it to take only twice as long.
What causes the increase in memory allocation?

**Comment by jlapeyre** [comment]
I edited your code a bit, to stop the warnings (The suggestion for `eye` is pretty awful, I hope that improves).

The line `w1 = Weeks.(laplaceelement)` is an error, it should be `w1 = Weeks(laplaceelement)`. It is most safe for benchmarking to make *everything* either a constant or to wrap it in a function.

I see that both real and complex computations take about the same time. The allocation difference is surprising. I don't see immediately where it is coming from.  I used both `@btime` and `@time` because I don't know how to make `@btime` give actual allocation information.

```julia
using InverseLaplace
using LinearAlgebra
using LinearAlgebra.LAPACK: gesv!
using BenchmarkTools

######  Function definitions

function randmatvec(N::Int64)
    # Initialize the matrix A  and the vector b for the equation (sI - A)x = b
    A = complex.(rand(N^2,N^2),rand(N^2,N^2))
    b = zeros(Complex{Float64},N^2)
    b[N*(N-1)] = complex.(1.0,0.0)
    return (A, b)
end

function matrixequation!(A::AbstractArray{T},s::T) where T
    # Returns the l.h.s. of the equation (sI - A)x = b
#    A .= s.*eye(A) .- A
    A .= s .* Matrix{eltype(A)}(I, size(A)) .- A
    return A
end

function solvematrixequation!(A::AbstractArray{T},b::AbstractVector{T},s::T) where T
    # Return the first element of the solution of (sI - A)x = b
    gesv!(matrixequation!(A,s),b)
    return b[1]
end

function laplaceelement(s::Complex{Float64}, N::Int64)
    # Wrapper for first element of x(s) = (sI -A)⁻¹b
    (A,b) = randmatvec(N)
    return solvematrixequation!(A,b,s)
end
######

function testweeks()
    N = 8
    laplaceelement1 = s -> laplaceelement(s, N)
    trange = range(0.0, stop=3.0, length=10^5)

    println("Float64")
    @time w1 = Weeks(laplaceelement1)

    println()
    println("Timing w1 on trange")
    @btime $w1.($trange)

    println()
    println("Allocation w1 on trange")
    @time w1.(trange)

    println()
    println("Complex{Float64}")
    @time w2 = Weeks(laplaceelement1, datatype=Complex)

    println()
    println("Timing w2 on trange")
    @btime $w2.($trange)

    println()
    println("Allocation w2 on trange")
    @time w2.(trange)

    return nothing
end
```

```julia
julia> testweeks()
Float64
  1.501657 seconds (2.69 M allocations: 156.318 MiB, 3.77% gc time)

Timing w1 on trange
  110.254 ms (2 allocations: 781.33 KiB)

Allocation w1 on trange
  0.112139 seconds (2 allocations: 781.328 KiB)

Complex{Float64}
  0.260090 seconds (47.91 k allocations: 26.590 MiB, 0.95% gc time)

Timing w2 on trange
  117.817 ms (2 allocations: 1.53 MiB)

Allocation w2 on trange
  0.139232 seconds (1.25 k allocations: 1.593 MiB)
```

**Comment by elisno** [comment]
I clearly need to upgrade to v.0.7.

I've been using the deprecated `linspace()` (v.0.6.2) and I suspect it's causing the overhead.
Your code does reduce the amount of allocations in the real case from 6 to 2, but the problem persists in the complex case.

I'll post the output from both versions for comparison.

`range()` is defined differently in [v0.6.2](https://docs.julialang.org/en/v0.6.2/stdlib/math/#Base.range). I'll have to use `trange = range(0.0, 3.0E-5, 10^5).

```julia
julia> testweeks()
Float64
  0.034899 seconds (1.79 k allocations: 24.269 MiB, 11.04% gc time)

Timing w1 on trange
  252.947 ms (2 allocations: 781.33 KiB)

Allocation w1 on trange
  0.256000 seconds (2 allocations: 781.328 KiB)

Complex{Float64}
  0.050426 seconds (4.40 k allocations: 24.405 MiB, 1.60% gc time)

Timing w2 on trange
  804.836 ms (37800002 allocations: 1.03 GiB)

Allocation w2 on trange
  0.797675 seconds (37.80 M allocations: 1.030 GiB, 14.16% gc time)
```

**Comment by jlapeyre** [comment]
> I've been using the deprecated linspace() (v.0.6.2) and I suspect it's causing the overhead.

I'm not sure if v0.6 is causing overhead. I just upgraded your example because I am using v0.7.  Deprecation warnings can sometimes kill performance, and I wanted to remove that variable. You had `collect(linspace(....`  which unnecessarily allocates. Just `linspace` or `range` will do.

**Comment by elisno** [comment]
So I've updated to v0.7 and I achieve similar performance as you do.
However, running `testweeks()` a second time shows twice as many allocations for the complex case as I expected.

```julia
julia> testweeks()
Float64
  1.788193 seconds (2.87 M allocations: 166.379 MiB, 4.47% gc time)

Timing w1 on trange
  185.681 ms (2 allocations: 781.33 KiB)

Allocation w1 on trange
  0.187465 seconds (2 allocations: 781.328 KiB)

Complex{Float64}
  0.181701 seconds (48.98 k allocations: 26.659 MiB, 34.43% gc time)

Timing w2 on trange
  205.688 ms (2 allocations: 1.53 MiB)

Allocation w2 on trange
  0.232658 seconds (1.28 k allocations: 1.601 MiB)



julia> testweeks()
Float64
  0.124562 seconds (1.50 k allocations: 24.287 MiB, 49.05% gc time)

Timing w1 on trange
  183.687 ms (2 allocations: 781.33 KiB)

Allocation w1 on trange
  0.187595 seconds (2 allocations: 781.328 KiB)

Complex{Float64}
  0.166740 seconds (35.93 k allocations: 25.974 MiB, 37.28% gc time)

Timing w2 on trange
  208.335 ms (2 allocations: 1.53 MiB)

Allocation w2 on trange
  0.209045 seconds (4 allocations: 1.526 MiB)

```

**Comment by elisno** [comment]
I'm not sure how, but both methods show the same amount of allocations (`1.50 k allocations: 24.287 MiB`).


A significant amount of time is spent calculating the `unm1` in `_laguerre(a::AbstractVector,x)` if the length of `trange` is increased.
Could performance be improved if `_laguerre(a::AbstractVector,x::AbstractArray)` is used instead? 
I keep getting a method error with the current type of `trange`.


My main concern is if `N` is increased. Calling `gesv!` allocates a lot of memory, which is expected.
However, this code performs an inverse Laplace transform on only a single vector element.
Iterating through each element would result in repeated calls to `gesv!`.

Could `func `in `weeks(func,...)` be a matrix valued function?

**Comment by elisno** [comment]
Since both methods give similar results, I'll close this issue.

I've created a seperate issue (#4)  regarding matrix valued functions.
